server:
  port: 8081
spring:
  application:
    name: fraud
  datasource:
    password: '123'
    url: jdbc:postgresql://192.168.99.103:5432/fraud
    username: 'postgres'
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
    hibernate:
      ddl-auto: create-drop
    show-sql: true